name: Update Minecraft Server Status

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Status-Skript ausführen
      run: python status_worker.py

    - name: Datei in GitHub committen und pushen
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add serverstatus.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update serverstatus.json [skip ci]" && git push)
